name: Remove old artifacts

on: push

concurrency:
  group: archive_removal
  cancel-in-progress: true

jobs:
  sleep:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sleep Action
      uses: juliangruber/sleep-action@v1.0.1
      with:
        time: 10m
    
    
  remove-old-artifacts:
    needs: sleep
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 seconds'
